DROP TABLE exercise IF EXISTS;
DROP TABLE food IF EXISTS;

CREATE TABLE exercise_types (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exercise_type_name    VARCHAR(30) NOT NULL
);

CREATE TABLE exercise (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id     INTEGER NOT NULL,
    date        TIMESTAMP NOT NULL,
    kilocalories    INTEGER NOT NULL
);
ALTER TABLE exercise ADD CONSTRAINT fk_exercise_types FOREIGN KEY (type_id) REFERENCES exercise_types (id);


CREATE TABLE food_names (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type    VARCHAR(30) NOT NULL
);

CREATE TABLE food (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_id     INTEGER NOT NULL,
    date        DATE NOT NULL,
    kilocalories    INTEGER NOT NULL
);
ALTER TABLE food ADD CONSTRAINT fk_food_names FOREIGN KEY (name_id) REFERENCES food_names (id);

